---
# tasks file for arillso.sshd

- name: add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration

- name: get openssh-version
  shell: executable=/bin/bash set -o pipefail && false | ssh -V 2>&1 | sed -r 's/.*_([0-9]*\.[0-9]).*/\1/g'
  changed_when: false
  register: sshd_version
  check_mode: no
  tags:
    - configuration

- name: set hostkeys according to openssh-version
  set_fact:
    ssh_host_key_files:
      [
        "/etc/ssh/ssh_host_rsa_key",
        "/etc/ssh/ssh_host_ecdsa_key",
        "/etc/ssh/ssh_host_ed25519_key",
      ]
  when: sshd_version.stdout >= '6.3' and not ssh_host_key_files
  tags:
    - configuration

- name: set hostkeys according to openssh-version
  set_fact:
    ssh_host_key_files:
      ["/etc/ssh/ssh_host_rsa_key", "/etc/ssh/ssh_host_ecdsa_key"]
  when: sshd_version.stdout >= '6.0' and not ssh_host_key_files
  tags:
    - configuration

- name: set hostkeys according to openssh-version
  set_fact:
    ssh_host_key_files: ["/etc/ssh/ssh_host_rsa_key"]
  when: sshd_version.stdout >= '5.3' and not ssh_host_key_files
  tags:
    - configuration

- name: set weak macs according to openssh-version if openssh >= 7.6
  set_fact:
    ssh_macs: "{{ ssh_macs_76_default }}"
  when: sshd_version.stdout >= '7.6' and not ssh_macs
  tags:
    - configuration

- name: set weak macs according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_macs: "{{ ssh_macs_66_weak }}"
  when: sshd_version.stdout >= '6.6' and ssh_server_weak_hmac and not ssh_macs
  tags:
    - configuration

- name: set macs according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_macs: "{{ ssh_macs_66_default }}"
  when: sshd_version.stdout >= '6.6' and not ssh_macs
  tags:
    - configuration

- name: set weak macs according to openssh-version
  set_fact:
    ssh_macs: "{{ ssh_macs_59_weak }}"
  when: sshd_version.stdout >= '5.9' and ssh_server_weak_hmac and not ssh_macs
  tags:
    - configuration

- name: set macs according to openssh-version
  set_fact:
    ssh_macs: "{{ ssh_macs_59_default }}"
  when: sshd_version.stdout >= '5.9' and not ssh_macs
  tags:
    - configuration

- name: set macs according to openssh-version
  set_fact:
    ssh_macs: "{{ ssh_macs_53_default }}"
  when: sshd_version.stdout >= '5.3' and not ssh_macs
  tags:
    - configuration

- name: set macs according to openssh-version
  set_fact:
    ssh_macs: "{{ ssh_macs_53_default }}"
  when: sshd_version.stdout >= '5.3' and not ssh_macs
  tags:
    - configuration

- name: set weak ciphers according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_ciphers: "{{ ssh_ciphers_66_weak }}"
  when: sshd_version.stdout >= '6.6' and ssh_server_cbc_required and not ssh_ciphers
  tags:
    - configuration

- name: set ciphers according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_ciphers: "{{ ssh_ciphers_66_default }}"
  when: sshd_version.stdout >= '6.6' and not ssh_ciphers
  tags:
    - configuration

- name: set weak ciphers according to openssh-version
  set_fact:
    ssh_ciphers: "{{ ssh_ciphers_53_weak }}"
  when: sshd_version.stdout >= '5.3' and ssh_server_cbc_required and not ssh_ciphers
  tags:
    - configuration

- name: set ciphers according to openssh-version
  set_fact:
    ssh_ciphers: "{{ ssh_ciphers_53_default }}"
  when: sshd_version.stdout >= '5.3' and not ssh_ciphers
  tags:
    - configuration

- name: set weak kex according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_kex: "{{ ssh_kex_66_weak }}"
  when: sshd_version.stdout >= '6.6' and ssh_server_weak_hmac and not ssh_kex
  tags:
    - configuration

- name: set kex according to openssh-version if openssh >= 6.6
  set_fact:
    ssh_kex: "{{ ssh_kex_66_default }}"
  when: sshd_version.stdout >= '6.6' and not ssh_kex
  tags:
    - configuration

- name: set weak kex according to openssh-version
  set_fact:
    ssh_kex: "{{ ssh_kex_59_weak }}"
  when: sshd_version.stdout >= '5.9' and ssh_server_weak_hmac and not ssh_kex
  tags:
    - configuration

- name: set kex according to openssh-version
  set_fact:
    ssh_kex: "{{ ssh_kex_59_default }}"
  when: sshd_version.stdout >= '5.9' and not ssh_kex
  tags:
    - configuration

- name: create sshd_config and set permissions to root/600
  become: true
  template:
    src: "opensshd.conf.j2"
    dest: "/etc/ssh/sshd_config"
    mode: 0600
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
    validate: "/usr/sbin/sshd -T -f %s"
  notify: restart sshd
  tags:
    - configuration

- name: create ssh_config and set permissions to root/644
  become: true
  template:
    src: "openssh.conf.j2"
    dest: "/etc/ssh/ssh_config"
    mode: 0644
    owner: "{{ ssh_owner }}"
    group: "{{ ssh_group }}"
  tags:
    - configuration
